# Generated by Django 4.2.5 on 2024-07-29 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
            ],
            options={
                "ordering": ["name", "estado"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrdemDeCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("undMedida", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Prefeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                (
                    "nascimento",
                    models.DateField(
                        default=datetime.date(2000, 1, 1),
                        verbose_name="data de nascimento",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=120, null=True)),
                ("cargo", models.URLField(blank=True, max_length=255, null=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemDeCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("entregue", models.BooleanField(default=False)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cidade",
                    ),
                ),
                (
                    "prefeitura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.prefeitura",
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(
                        through="cadastros.ItemOrdemDeCompra", to="cadastros.produto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemordemdecompra",
            name="ordem_de_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.ordemdecompra",
            ),
        ),
        migrations.AddField(
            model_name="itemordemdecompra",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastros.produto"
            ),
        ),
    ]
