# Generated by Django 4.2.5 on 2024-03-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=120, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "rede_social",
                    models.URLField(
                        blank=True,
                        default="Não informado",
                        help_text="Informe o link do Instagram, Facebook ou outra rede social",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Salario"
                    ),
                ),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cidade",
                    ),
                ),
            ],
        ),
    ]
