# Generated by Django 4.2.5 on 2024-07-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="cargo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
