# Generated by Django 5.1.2 on 2024-10-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_profile_bio_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
